"use client";

import React, { useState } from "react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Search } from "lucide-react";

const PartsInventoryPage = () => {
  const [searchTerm, setSearchTerm] = useState("");

  // Parse the parts data from the text file
 const enhancedPartsData = [
    // Initial Components
    {
        id: 1001,
        part: "Tubular Steel Frame (powder coated satin black)",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Chassis",
        category: "Initial Components",
        notes: "Satin black powder coating ($699 upgrade on order)",
        dependencies: [],
        estimatedInstallTime: "1-2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "27-30",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 1002,
        part: "Composite Body",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Body",
        category: "Initial Components",
        notes: "Pre-cut with requested openings ($149 upgrade on order)",
        dependencies: [1001],
        estimatedInstallTime: "4-6 hours",
        installDate: null,
        installDifficulty: "Hard",
        manualPageReference: "331-340",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 1003,
        part: "Laser-cut 6061-T6 Aluminum Panels",
        quantity: 66,
        quantityReceived: 0,
        status: "Not Received",
        section: "Various",
        category: "Initial Components",
        notes: "For cockpit, trunk, and engine bay panels",
        dependencies: [1001],
        estimatedInstallTime: "12-16 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "23-26, 118-167, 218-222",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 1004,
        part: "Pre-packaged Rivets (1/8\" and 3/16\")",
        quantity: 1200,
        quantityReceived: 0,
        status: "Not Received",
        section: "Various",
        category: "Initial Components",
        notes: "For aluminum panel installation",
        dependencies: [1003],
        estimatedInstallTime: "N/A",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "28-30",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 1005,
        part: "Certificate of Origin with Nameplate",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Documentation",
        category: "Initial Components",
        notes: "Important for registration",
        dependencies: [],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "15, 298-299",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },

    // Front Suspension
    {
        id: 2001,
        part: "Tubular Upper Control Arms",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Front Suspension",
        category: "Front Suspension",
        notes: "",
        dependencies: [1001],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "33-38",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 2002,
        part: "Tubular Lower Control Arms",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Front Suspension",
        category: "Front Suspension",
        notes: "",
        dependencies: [1001],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "31-33",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 2003,
        part: "Koni Coil-over Shocks (Front)",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Front Suspension",
        category: "Front Suspension",
        notes: "For standard width suspension package",
        dependencies: [2001, 2002],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "38-45",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 2004,
        part: "Front Springs (500 lb)",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Front Suspension",
        category: "Front Suspension",
        notes: "",
        dependencies: [2003],
        estimatedInstallTime: "Included with shocks",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "38-45",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 2005,
        part: "Upper Ball Joints",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Front Suspension",
        category: "Front Suspension",
        notes: "",
        dependencies: [2001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "33-38",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 2006,
        part: "Lower Ball Joints",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Front Suspension",
        category: "Front Suspension",
        notes: "",
        dependencies: [2002],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "31-33",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 2007,
        part: "Spindles (marked DSS/PSS)",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Front Suspension",
        category: "Front Suspension",
        notes: "Note that DSS mounts on passenger side, PSS on driver side for Roadster",
        dependencies: [2005, 2006],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "45-49",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 2008,
        part: "Front Wheel Hubs",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Front Suspension",
        category: "Front Suspension",
        notes: "",
        dependencies: [2007],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "48-49",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 2009,
        part: "Steering Arms",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Front Suspension",
        category: "Front Suspension",
        notes: "",
        dependencies: [2007],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "48",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 2010,
        part: "Grease Fittings",
        quantity: 12,
        quantityReceived: 0,
        status: "Not Received",
        section: "Front Suspension",
        category: "Front Suspension",
        notes: "For control arms, ball joints, and tie rod ends",
        dependencies: [2001, 2002],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "31-38",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },

    // Power Steering Components
    {
        id: 3001,
        part: "Power Steering Rack",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Steering System",
        category: "Power Steering Components",
        notes: "Power steering upgrade ($299)",
        dependencies: [1001],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "138-143",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 3002,
        part: "Power Steering Pump",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Steering System",
        category: "Power Steering Components",
        notes: "Included with power steering package",
        dependencies: [3001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "138-143",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 3003,
        part: "Power Steering Lines",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Steering System",
        category: "Power Steering Components",
        notes: "Set",
        dependencies: [3001, 3002],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "138-143",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 3004,
        part: "Steering Rack Mounting Hardware",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Steering System",
        category: "Power Steering Components",
        notes: "Set",
        dependencies: [3001],
        estimatedInstallTime: "Included with rack",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "138-143",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 3005,
        part: "Outer Tie Rod Ends",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Steering System",
        category: "Power Steering Components",
        notes: "",
        dependencies: [3001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "139-143",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 3006,
        part: "Steering Universal Joints",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Steering System",
        category: "Power Steering Components",
        notes: "",
        dependencies: [3001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "143-152",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 3007,
        part: "Nickel-Plated Lower Steering Shaft",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Steering System",
        category: "Power Steering Components",
        notes: "",
        dependencies: [3001, 3006],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "149-152",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 3008,
        part: "Upper Steering Shaft",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Steering System",
        category: "Power Steering Components",
        notes: "",
        dependencies: [3006, 3007],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "152-156",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 3009,
        part: "Steering Bearings",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Steering System",
        category: "Power Steering Components",
        notes: "",
        dependencies: [3008],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "143-149",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 3010,
        part: "Wood Steering Wheel",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Steering System",
        category: "Power Steering Components",
        notes: "",
        dependencies: [3008],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "316-317",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 3011,
        part: "Steering Boss",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Steering System",
        category: "Power Steering Components",
        notes: "",
        dependencies: [3010],
        estimatedInstallTime: "Included with wheel",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "316-317",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 3012,
        part: "Ceramic Factory Five Badge",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Steering System",
        category: "Power Steering Components",
        notes: "For steering wheel center",
        dependencies: [3010],
        estimatedInstallTime: "10 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "500-502",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },

    // IRS Rear Suspension
    {
        id: 4001,
        part: "IRS Center Section (with 3.55 gears)",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Rear Suspension",
        category: "IRS Rear Suspension",
        notes: "$1,750 upgraded component",
        dependencies: [1001],
        estimatedInstallTime: "3 hours",
        installDate: null,
        installDifficulty: "Hard",
        manualPageReference: "82-93",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 4002,
        part: "IRS Spindles",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Rear Suspension",
        category: "IRS Rear Suspension",
        notes: "Included with IRS package",
        dependencies: [4001],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "83-88",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 4003,
        part: "Upper Control Arms",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Rear Suspension",
        category: "IRS Rear Suspension",
        notes: "",
        dependencies: [1001, 4001],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "90-102",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 4004,
        part: "Lower Control Arms",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Rear Suspension",
        category: "IRS Rear Suspension",
        notes: "",
        dependencies: [1001, 4001],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "90-102",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 4005,
        part: "Toe Adjustment Arms",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Rear Suspension",
        category: "IRS Rear Suspension",
        notes: "",
        dependencies: [1001, 4001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "92, 98-99",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 4006,
        part: "CV Axles",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Rear Suspension",
        category: "IRS Rear Suspension",
        notes: "",
        dependencies: [4001, 4002],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "101-102",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 4007,
        part: "Koni Coil-over Shocks (Rear)",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Rear Suspension",
        category: "IRS Rear Suspension",
        notes: "",
        dependencies: [4003, 4004],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "107-113",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 4008,
        part: "Rear Springs (400 lb)",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Rear Suspension",
        category: "IRS Rear Suspension",
        notes: "",
        dependencies: [4007],
        estimatedInstallTime: "Included with shocks",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "107-113",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 4009,
        part: "Polyurethane Bushings",
        quantity: 16,
        quantityReceived: 0,
        status: "Not Received",
        section: "Rear Suspension",
        category: "IRS Rear Suspension",
        notes: "Various sizes",
        dependencies: [4003, 4004, 4005],
        estimatedInstallTime: "Included with arms",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "88-92",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 4010,
        part: "Mounting Hardware",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Rear Suspension",
        category: "IRS Rear Suspension",
        notes: "Set",
        dependencies: [4001, 4002, 4003, 4004, 4005],
        estimatedInstallTime: "Included with components",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "92-117",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },

    // Brake System
    {
        id: 5001,
        part: "Wilwood 12.88\" Front Brakes (Red)",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Front Brakes",
        category: "Brake System",
        notes: "$1,850 upgraded front brakes",
        dependencies: [2008],
        estimatedInstallTime: "3 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "49-58",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 5002,
        part: "Wilwood Rear Brakes for IRS (Red)",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Rear Brakes",
        category: "Brake System",
        notes: "$2,299 upgraded rear brakes",
        dependencies: [4002],
        estimatedInstallTime: "3 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "113",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 5003,
        part: "Wilwood Pedal Assembly",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Pedal Box",
        category: "Brake System",
        notes: "",
        dependencies: [1001],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "120-132",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 5004,
        part: "Master Cylinders",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Pedal Box",
        category: "Brake System",
        notes: "",
        dependencies: [5003],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "129-132",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 5005,
        part: "Brake Lines (3/16\")",
        quantity: 12,
        quantityReceived: 0,
        status: "Not Received",
        section: "Brake System",
        category: "Brake System",
        notes: "Various lengths",
        dependencies: [5003, 5004],
        estimatedInstallTime: "4 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "192-215",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 5006,
        part: "Brake Line Fittings",
        quantity: 20,
        quantityReceived: 0,
        status: "Not Received",
        section: "Brake System",
        category: "Brake System",
        notes: "Various types",
        dependencies: [5005],
        estimatedInstallTime: "Included with lines",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "192-215",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 5007,
        part: "Brake Reservoirs",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Brake System",
        category: "Brake System",
        notes: "",
        dependencies: [5004],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "192-200",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 5008,
        part: "Brake Line Clips",
        quantity: 24,
        quantityReceived: 0,
        status: "Not Received",
        section: "Brake System",
        category: "Brake System",
        notes: "",
        dependencies: [5005],
        estimatedInstallTime: "Included with lines",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "204-215",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 5009,
        part: "Flexible Brake Hoses",
        quantity: 4,
        quantityReceived: 0,
        status: "Not Received",
        section: "Brake System",
        category: "Brake System",
        notes: "",
        dependencies: [5001, 5002, 5005],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "200-215",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 5010,
        part: "Emergency Brake Handle",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Emergency Brake",
        category: "Brake System",
        notes: "",
        dependencies: [1001],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "266-281",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 5011,
        part: "E-Brake Cables",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Emergency Brake",
        category: "Brake System",
        notes: "",
        dependencies: [5010, 5002],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "281-284",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },

    // Fuel System
    {
        id: 6001,
        part: "Fuel Tank",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Fuel System",
        category: "Fuel System",
        notes: "",
        dependencies: [1001],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "168-185",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 6002,
        part: "In-Tank EFI Fuel System",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Fuel System",
        category: "Fuel System",
        notes: "$645 upgrade",
        dependencies: [6001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "173-179",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 6003,
        part: "Fuel Tank Mounting Hardware",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Fuel System",
        category: "Fuel System",
        notes: "Set",
        dependencies: [6001],
        estimatedInstallTime: "Included with tank",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "168-185",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 6004,
        part: "Fuel Level Sending Unit",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Fuel System",
        category: "Fuel System",
        notes: "",
        dependencies: [6001],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "179-181",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 6005,
        part: "Fuel Filler Neck",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Fuel System",
        category: "Fuel System",
        notes: "",
        dependencies: [6001],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "181-183",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 6006,
        part: "Polished Aston Lemans Aluminum Fuel Cap",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Fuel System",
        category: "Fuel System",
        notes: "",
        dependencies: [1002, 6005],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "402-405, 458-459",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 6007,
        part: "Fuel Lines (1/4\" and 5/16\")",
        quantity: 6,
        quantityReceived: 0,
        status: "Not Received",
        section: "Fuel System",
        category: "Fuel System",
        notes: "Various lengths",
        dependencies: [6001, 6002],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "188-191",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 6008,
        part: "Fuel Line Fittings",
        quantity: 12,
        quantityReceived: 0,
        status: "Not Received",
        section: "Fuel System",
        category: "Fuel System",
        notes: "Various types",
        dependencies: [6007],
        estimatedInstallTime: "Included with lines",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "188-191",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 6009,
        part: "Fuel Filter",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Fuel System",
        category: "Fuel System",
        notes: "",
        dependencies: [6007],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "185-188",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },

    // Cooling System
    {
        id: 7001,
        part: "Aluminum Radiator",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Cooling System",
        category: "Cooling System",
        notes: "",
        dependencies: [1001, 1002],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "250-256",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 7002,
        part: "Electric Cooling Fan",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Cooling System",
        category: "Cooling System",
        notes: "",
        dependencies: [7001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "250-254",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 7003,
        part: "Fan Mounting Hardware",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Cooling System",
        category: "Cooling System",
        notes: "Set",
        dependencies: [7002],
        estimatedInstallTime: "Included with fan",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "250-254",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 7004,
        part: "Stainless Steel Radiator Hose Kit",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Cooling System",
        category: "Cooling System",
        notes: "",
        dependencies: [7001],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "256-261",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 7005,
        part: "Radiator Cap",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Cooling System",
        category: "Cooling System",
        notes: "",
        dependencies: [7001],
        estimatedInstallTime: "5 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "263",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 7006,
        part: "Overflow Tank",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Cooling System",
        category: "Cooling System",
        notes: "",
        dependencies: [7001],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "261-263",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 7007,
        part: "185° Thermostat Switch",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Cooling System",
        category: "Cooling System",
        notes: "For fan activation",
        dependencies: [7002],
        estimatedInstallTime: "15 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "263-264",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },

    // Engine & Exhaust
    {
        id: 8001,
        part: "351W Engine Mounts",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Engine Installation",
        category: "Engine & Exhaust",
        notes: "Set",
        dependencies: [1001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "224-228",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 8002,
        part: "351W Headers",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Exhaust System",
        category: "Engine & Exhaust",
        notes: "$799 upgrade",
        dependencies: [8001],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "238-240",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 8003,
        part: "Side Exhaust System",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Exhaust System",
        category: "Engine & Exhaust",
        notes: "$999 upgrade",
        dependencies: [8002, 1002],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "502-507",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 8004,
        part: "31-Spline Driveshaft (8.38\")",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Drivetrain",
        category: "Engine & Exhaust",
        notes: "For TKO/TKX transmission",
        dependencies: [8001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "290-292",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 8005,
        part: "Hydraulic Clutch Master Cylinder Kit",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Pedal Box",
        category: "Engine & Exhaust",
        notes: "$140 upgrade",
        dependencies: [5003],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "129-132",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },

    // Electrical Components
    {
        id: 9001,
        part: "Custom Chassis Wiring Harness",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Electrical System",
        category: "Electrical Components",
        notes: "",
        dependencies: [1001],
        estimatedInstallTime: "6 hours",
        installDate: null,
        installDifficulty: "Hard",
        manualPageReference: "218",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 9002,
        part: "Ignition Switch",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Dash/Gauges",
        category: "Electrical Components",
        notes: "",
        dependencies: [9001],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "299-310",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 9003,
        part: "Headlight Switch",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Dash/Gauges",
        category: "Electrical Components",
        notes: "",
        dependencies: [9001],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "299-310",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 9004,
        part: "Hi-Low Beam Switch",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Dash/Gauges",
        category: "Electrical Components",
        notes: "",
        dependencies: [9001],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "299-310",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 9005,
        part: "Starter Solenoid",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Electrical System",
        category: "Electrical Components",
        notes: "",
        dependencies: [9001],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "232-238",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 9006,
        part: "Horn Button",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Dash/Gauges",
        category: "Electrical Components",
        notes: "",
        dependencies: [9001, 3010],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "310-316",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 9007,
        part: "Dash Indicator Lights",
        quantity: 6,
        quantityReceived: 0,
        status: "Not Received",
        section: "Dash/Gauges",
        category: "Electrical Components",
        notes: "Set",
        dependencies: [9001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "299-310",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 9008,
        part: "Battery Cables/Ground Strap",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Electrical System",
        category: "Electrical Components",
        notes: "Set",
        dependencies: [9001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "232-238",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 9009,
        part: "Speedometer Sending Unit",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Electrical System",
        category: "Electrical Components",
        notes: "",
        dependencies: [9001],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "264-266",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 9010,
        part: "Vintage GPS 7-Gauge Set",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Dash/Gauges",
        category: "Electrical Components",
        notes: "$550 upgrade",
        dependencies: [9001],
        estimatedInstallTime: "3 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "299-310",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 9011,
        part: "4-Way Battery Cut-Off Switch",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Electrical System",
        category: "Electrical Components",
        notes: "",
        dependencies: [9001, 9008],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "",
        image: null,
        location: null,
        isOptional: true,
        inspectionNotes: ""
    },

    // Interior Components
    {
        id: 10001,
        part: "Black Leather Seats",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Interior",
        category: "Interior Components",
        notes: "$775 upgrade",
        dependencies: [1001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "296-298",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 10002,
        part: "5-Point Harnesses (2\")",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Interior",
        category: "Interior Components",
        notes: "",
        dependencies: [10001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "439-446",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 10003,
        part: "Carpet Set",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Interior",
        category: "Interior Components",
        notes: "",
        dependencies: [1003],
        estimatedInstallTime: "4 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "428-439",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 10004,
        part: "Emergency Brake Boot",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Interior",
        category: "Interior Components",
        notes: "",
        dependencies: [5010, 10003],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "441-443",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 10005,
        part: "Interior Rearview Mirror",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Interior",
        category: "Interior Components",
        notes: "",
        dependencies: [1002],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "481-485",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 10006,
        part: "Door Latches",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Doors",
        category: "Interior Components",
        notes: "",
        dependencies: [1002],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "382-385",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 10007,
        part: "Aluminum Dash with Vinyl",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Dash/Gauges",
        category: "Interior Components",
        notes: "",
        dependencies: [1001, 9010],
        estimatedInstallTime: "3 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "299-310",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 10008,
        part: "Shifter Boot",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Interior",
        category: "Interior Components",
        notes: "",
        dependencies: [10003],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "446-450",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 10009,
        part: "Seat Tracks",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Interior",
        category: "Interior Components",
        notes: "",
        dependencies: [10001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "296-298",
        image: null,
        location: null,
        isOptional: true,
        inspectionNotes: ""
    },
    {
        id: 10010,
        part: "A/C System Components",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "A/C System",
        category: "Interior Components",
        notes: "$1,475 upgrade",
        dependencies: [1001, 8001],
        estimatedInstallTime: "6 hours",
        installDate: null,
        installDifficulty: "Hard",
        manualPageReference: "",
        image: null,
        location: null,
        isOptional: true,
        inspectionNotes: ""
    },
    {
        id: 10011,
        part: "Sun Visor Set",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Interior",
        category: "Interior Components",
        notes: "$125 upgrade",
        dependencies: [1002],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "",
        image: null,
        location: null,
        isOptional: true,
        inspectionNotes: ""
    },

    // Exterior Components
    {
        id: 11001,
        part: "DOT Approved Windshield",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Windshield",
        category: "Exterior Components",
        notes: "",
        dependencies: [1002],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "373-377",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 11002,
        part: "Wind Wing Set",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Windshield",
        category: "Exterior Components",
        notes: "",
        dependencies: [11001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "",
        image: null,
        location: null,
        isOptional: true,
        inspectionNotes: ""
    },
    {
        id: 11003,
        part: "DOT Approved Headlights",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Exterior Lights",
        category: "Exterior Components",
        notes: "",
        dependencies: [1002, 9001],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "413-415, 450-456",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 11004,
        part: "Turn Signals",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Exterior Lights",
        category: "Exterior Components",
        notes: "",
        dependencies: [1002, 9001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "406-408, 456-457",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 11005,
        part: "Taillights",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Exterior Lights",
        category: "Exterior Components",
        notes: "",
        dependencies: [1002, 9001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "406, 457",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 11006,
        part: "License Plate Light and Bracket",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Exterior Lights",
        category: "Exterior Components",
        notes: "",
        dependencies: [1002, 9001],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "408-411",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 11007,
        part: "GT400 Polished Side Mirrors",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Exterior",
        category: "Exterior Components",
        notes: "Driver side included, passenger side is $59 upgrade",
        dependencies: [1002],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "397-401, 493-494",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 11008,
        part: "Hood Hinges with Supports",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Hood",
        category: "Exterior Components",
        notes: "Set",
        dependencies: [1002],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "343-351",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 11009,
        part: "Plastic Hood Scoop",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Hood",
        category: "Exterior Components",
        notes: "",
        dependencies: [1002],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "357-373",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 11010,
        part: "Hidden Trunk Hinge Kit",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Trunk",
        category: "Exterior Components",
        notes: "",
        dependencies: [1002],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "386-388",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
     {
        id: 11011,
        part: "Trunk Gas Strut Kit",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Trunk",
        category: "Exterior Components",
        notes: "",
        dependencies: [11010],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "462-466",
        image: null,
        location: null,
        isOptional: true,
        inspectionNotes: ""
    },
    {
        id: 11012,
        part: "Chrome Rollbar",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Safety",
        category: "Exterior Components",
        notes: "$499 upgrade",
        dependencies: [1001, 1002],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "317-322, 417-423",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 11013,
        part: "1.50\" Rollbar Grommet Set",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Safety",
        category: "Exterior Components",
        notes: "$94 upgrade",
        dependencies: [11012],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "423-424",
        image: null,
        location: null,
        isOptional: true,
        inspectionNotes: ""
    },
    {
        id: 11014,
        part: "Side Louvers",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Body",
        category: "Exterior Components",
        notes: "",
        dependencies: [1002],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "415-417, 460-462",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 11015,
        part: "Brake Duct Wire Mesh Set",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Body",
        category: "Exterior Components",
        notes: "",
        dependencies: [1002],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "",
        image: null,
        location: null,
        isOptional: true,
        inspectionNotes: ""
    },
    {
        id: 11016,
        part: "Factory Five Nose and Tail Badges",
        quantity: 2,
        quantityReceived: 0,
        status: "Not Received",
        section: "Exterior",
        category: "Exterior Components",
        notes: "",
        dependencies: [1002],
        estimatedInstallTime: "30 minutes",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },

    // Wheels and Tires
    {
        id: 12001,
        part: "18\" Halibrand Style Wheels",
        quantity: 4,
        quantityReceived: 0,
        status: "Not Received",
        section: "Wheels/Tires",
        category: "Wheels and Tires",
        notes: "Part of $3,699 wheel/tire package",
        dependencies: [2008, 4002],
        estimatedInstallTime: "1 hour",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "518-519",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 12002,
        part: "Tires",
        quantity: 4,
        quantityReceived: 0,
        status: "Not Received",
        section: "Wheels/Tires",
        category: "Wheels and Tires",
        notes: "Part of $3,699 wheel/tire package",
        dependencies: [12001],
        estimatedInstallTime: "Included with wheels",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "518-519",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 12003,
        part: "Lug Nuts",
        quantity: 20,
        quantityReceived: 0,
        status: "Not Received",
        section: "Wheels/Tires",
        category: "Wheels and Tires",
        notes: "5 per wheel",
        dependencies: [12001],
        estimatedInstallTime: "Included with wheels",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "518-519",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },

    // Fasteners and Hardware
    {
        id: 13001,
        part: "Zinc Plated Fasteners",
        quantity: 1600,
        quantityReceived: 0,
        status: "Not Received",
        section: "Various",
        category: "Fasteners and Hardware",
        notes: "Various sizes",
        dependencies: [],
        estimatedInstallTime: "N/A",
        installDate: null,
        installDifficulty: "N/A",
        manualPageReference: "538",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 13002,
        part: "Chrome and Stainless Steel Fasteners",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Various",
        category: "Fasteners and Hardware",
        notes: "Various types",
        dependencies: [],
        estimatedInstallTime: "N/A",
        installDate: null,
        installDifficulty: "N/A",
        manualPageReference: "538",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 13003,
        part: "Quick-Jack Components",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Body Mounting",
        category: "Fasteners and Hardware",
        notes: "Set",
        dependencies: [1001, 1002],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Medium",
        manualPageReference: "334-340",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 13004,
        part: "Weatherstripping",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Body Mounting",
        category: "Fasteners and Hardware",
        notes: "Various types",
        dependencies: [1001, 1002],
        estimatedInstallTime: "2 hours",
        installDate: null,
        installDifficulty: "Easy",
        manualPageReference: "466-469",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },

    // Documentation
    {
        id: 14001,
        part: "Assembly Manual",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Documentation",
        category: "Documentation",
        notes: "",
        dependencies: [],
        estimatedInstallTime: "N/A",
        installDate: null,
        installDifficulty: "N/A",
        manualPageReference: "N/A",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    },
    {
        id: 14002,
        part: "Wiring Diagrams",
        quantity: 1,
        quantityReceived: 0,
        status: "Not Received",
        section: "Documentation",
        category: "Documentation",
        notes: "Set",
        dependencies: [],
        estimatedInstallTime: "N/A",
        installDate: null,
        installDifficulty: "N/A",
        manualPageReference: "N/A",
        image: null,
        location: null,
        isOptional: false,
        inspectionNotes: ""
    }
];
  // Get unique categories
  const categories = [...new Set(partsData.map((item) => item.category))];

  // Filter parts based on search term
  const filteredParts = partsData.filter(
    (part) =>
      part.part.toLowerCase().includes(searchTerm.toLowerCase()) ||
      part.section.toLowerCase().includes(searchTerm.toLowerCase()) ||
      part.category.toLowerCase().includes(searchTerm.toLowerCase())
  );

  // Group parts by category
  const groupedParts = categories
    .map((category) => ({
      category,
      parts: filteredParts.filter((part) => part.category === category),
    }))
    .filter((group) => group.parts.length > 0);

  // Count parts by category for badges
  const categoryCount = categories.reduce(
    (acc, category) => {
      acc[category] = enhancedPartsData.filter(
        (part) => part.category === category
      ).length;
      return acc;
    },
    {} as Record<string, number>
  );

  return (
    <div className="container mx-auto px-4 py-8 max-w-8xl">
      <div className="flex flex-col space-y-8">
        {/* Header */}
        <div className="flex flex-col space-y-4 md:flex-row md:items-center md:justify-between md:space-y-0">
          <div>
            <h1 className="text-2xl font-bold">Parts Inventory</h1>
            <p className="text-gray-500">I think we&apos;re missing a piece</p>
          </div>
        </div>
        <div className="relative mt-2">
            <Search className="absolute left-2 top-2.5 h-4 w-4 text-slate-400" />
            <Input
              placeholder="Search parts, sections or categories..."
              className="pl-8"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
        <Accordion type="multiple" defaultValue={categories}>
          {groupedParts.map((group) => (
            <AccordionItem key={group.category} value={group.category}>
              <AccordionTrigger className="text-lg font-semibold hover:no-underline">
                <div className="flex items-center gap-2">
                  {group.category}
                  <Badge variant="secondary">
                    {group.parts.length}/{categoryCount[group.category]}
                  </Badge>
                </div>
              </AccordionTrigger>
              <AccordionContent>
                <div className="overflow-x-auto">
                  <div className="min-w-full border  rounded-md">
                    <div className="grid grid-cols-12  p-3 font-medium text-primary-400">
                      <div className="col-span-6">Part</div>
                      <div className="col-span-2">Quantity</div>
                      <div className="col-span-4">Assembly Section</div>
                    </div>
                    <div className="divide-y">
                      {group.parts.map((part: { part: string | number | bigint | boolean | React.ReactElement<unknown, string | React.JSXElementConstructor<any>> | Iterable<React.ReactNode> | React.ReactPortal | Promise<string | number | bigint | boolean | React.ReactPortal | React.ReactElement<unknown, string | React.JSXElementConstructor<any>> | Iterable<React.ReactNode> | null | undefined> | null | undefined; quantity: string | number | bigint | boolean | React.ReactElement<unknown, string | React.JSXElementConstructor<any>> | Iterable<React.ReactNode> | React.ReactPortal | Promise<string | number | bigint | boolean | React.ReactPortal | React.ReactElement<unknown, string | React.JSXElementConstructor<any>> | Iterable<React.ReactNode> | null | undefined> | null | undefined; section: string | number | bigint | boolean | React.ReactElement<unknown, string | React.JSXElementConstructor<any>> | Iterable<React.ReactNode> | React.ReactPortal | Promise<string | number | bigint | boolean | React.ReactPortal | React.ReactElement<unknown, string | React.JSXElementConstructor<any>> | Iterable<React.ReactNode> | null | undefined> | null | undefined; }, idx: any) => (
                        <div
                          key={`${part.part}-${idx}`}
                          className="grid grid-cols-12 p-3 hover:bg-accent/50"
                        >
                          <div className="col-span-6 font-medium">
                            {part.part}
                          </div>
                          <div className="col-span-2">{part.quantity}</div>
                          <div className="col-span-4">
                            <Badge variant="outline" className="mr-1">
                              {part.section}
                            </Badge>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </div>
  );
};

export default PartsInventoryPage;
